spring:
  jpa:
    hibernate:
      ddl-auto: update
#      update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      database: mysql
      database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3307/automotive?createDatabaseIfNotExist=true
    username: root
    password:
